name: Bug Report
description: Report a bug in myogait
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal code or steps to reproduce the issue.
      placeholder: |
        ```python
        from myogait import extract
        data = extract("video.mp4", model="mediapipe")
        # Error occurs here...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead? Include the full traceback if applicable.
    validations:
      required: true

  - type: dropdown
    id: pose-model
    attributes:
      label: Pose estimation backend
      options:
        - mediapipe
        - yolo
        - sapiens-quick
        - sapiens-mid
        - sapiens-top
        - vitpose
        - vitpose-large
        - vitpose-huge
        - rtmw
        - hrnet
        - mmpose
        - N/A
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: myogait version
      placeholder: "0.3.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information (GPU, video format, etc.)
